### ISSUE TITLE
Docs mention RSA-PKCS1-v1_5, code uses RSA-OAEP

### ISSUE THREAD

**Issue by mikemaccana** [infotechinc/public-key-encryption-in-browser#2]
Hi there Charles! Just reading your excellent FluentConf talk and checking out these examples. I notice that although the doc says:

> This example uses RSA-PKCS1-v1_5 to encrypt a random 128-bit AES key

But `createAndSaveAKeyPair` on https://github.com/infotechinc/public-key-encryption-in-browser/blob/master/pkcrypto.js#L47 uses `name: RSA-OAEP`. 

Also per section 19 of the WebCrypto spec, isn't RSA-PKCS1-v1_5 is used for 'sign' and 'verify' not 'encrypt' and 'decrypt'

Should the doc read the following instead:

> This example uses RSA-OAEP to encrypt a random 128-bit AES key

Thanks!

**Comment by engelke** [comment]
You found two bugs in a single word. The original documentation should have referred to RSAES-PKCS1-v1-5, not RSA-PKCS1-v1_5. That was an RSA encryption algorithm that I used when I first posted this. But it was removed from the Web Cryptography API specification last fall, so I changed to RSA-OAEP and forgot to update the documentation.

Now it's fixed.

Thanks for reading this example. I hope it is useful to you.
